substitutions:
  friendly_name: "Device Name"
  name: device-name
  icon: mdi:lightbulb
  
  password: !secret password
  encryption_key: !secret encryption_key  
  
  wifi_ssid: !secret wifi_ssid
  wifi_pswd: !secret wifi_password


  #### Additional packages
  
  ## Second SSID
  # wifi_ssid2: !secret wifi_ssid2
  # wifi_pswd2: !secret wifi_password2
  
  ## Static IP
  # ip: 192.168.x.x
  # ip_com: 192.168.x.x
  # gateway: !secret gateway
  # subnet: !secret subnet
  
  ## HTU21 Sensor
  # i2c_sda: "1"
  # i2c_scl: "3"
  # htu21_update_interval: 60s
  
  ## DS18B20 Sensor
  # ds18b20_adress: "0x0000000000000000"
  # ds18b20_pin: GPIO0
  
#########################################

packages:
  remote_package:
    url: !secret github_url
    ref: main
    refresh: !secret refresh_time
    files:
      - packages/default_config.yaml
      - packages/default_sensors.yaml
      - packages/esp8266_specific.yaml
      - packages/wifi_dhcp.yaml
      - packages/sonoff_basic_light.yaml
