### GAS meter package
# Substitutions needed
#
# substitutions:
#   gas_meter_pin: GPIO13
#   gas_meter_factor: "0.01"

sensor:
  - platform: pulse_meter
    pin: ${gas_meter_pin}
    unit_of_measurement: 'm³/min'
    name: 'Usage'
    icon: "mdi:fire"
    internal_filter: 50ms
    internal_filter_mode: PULSE
    accuracy_decimals: 2
    filters:
      - multiply: ${gas_meter_factor}
    total:
      name: "Total"
      icon: "mdi:fire"
      unit_of_measurement: "m³"
      device_class: gas
      state_class: "total_increasing"
      accuracy_decimals: 2
      filters:
        - multiply: ${gas_meter_factor}
