# Device Specific Config shelly 1 light

esp8266:
  board: esp01_1m
  restore_from_flash: true

globals:
  - id: switch_counter
    type: int
    restore_value: false
    initial_value: '0'

script:
  - id: reset_counter_script
    mode: restart
    then:
      - delay: 1s
      - lambda: |-
          id(switch_counter) = 0;

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_1_relay

light:
  - platform: binary
    name: ""
    output: shelly_1_relay
    id: lightid
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Input"
    disabled_by_default: true
    on_state:
      - light.toggle: lightid
      - lambda: |-
          id(switch_counter) += 1;
      - script.execute: reset_counter_script
      - if:
          condition:
            lambda: 'return id(switch_counter) >= 10;'
          then:
            - logger.log: "Switch toggled 10 times. Rebooting!"
            - button.press: restart_button
    internal: true
    id: switchid
