### Device Specific Config Shelly 1 as switch
# Substitutions needed
#
# substitutions:
#   icon: mdi:switch
 
esp8266:
  board: esp01_1m
  restore_from_flash: true

globals:
  - id: switch_counter
    type: int
    restore_value: false
    initial_value: '0'

script:
  - id: reset_counter_script
    mode: restart
    then:
      - delay: 1s
      - lambda: |-
          id(switch_counter) = 0;

# Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Input"
    disabled_by_default: true
    on_state:
      - switch.toggle: relay
      - lambda: |-
          id(switch_counter) += 1;
      - script.execute: reset_counter_script
      - if:
          condition:
            lambda: 'return id(switch_counter) >= 10;'
          then:
            - logger.log: "Switch toggled 10 times. Rebooting!"
            - button.press: restart_button

# Relay
switch:
  - platform: gpio
    name: ""
    pin: GPIO4
    id: relay
    icon: ${icon}
    restore_mode: RESTORE_DEFAULT_OFF
