# Sonoff T3 template

esp8266:
  board: esp01_1m
  restore_from_flash: true
  
output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
    
  - platform: gpio
    pin: GPIO5
    id: relay_2
    
  - platform: gpio
    pin: GPIO4
    id: relay_3

  # BLUE LED
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
    
  - platform: binary
    name: "1"
    id: light_1
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF
    
  - platform: binary
    name: "2"
    id: light_2
    output: relay_2
    restore_mode: RESTORE_DEFAULT_OFF
    
  - platform: binary
    name: "3"
    id: light_3
    output: relay_3
    restore_mode: RESTORE_DEFAULT_OFF
    
  # BLUE LED
  - platform: monochromatic
    name: "Blue LED"
    output: blue_led
    internal: true
    id: blue_led_light
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Touchpad 1"
    disabled_by_default: true
    on_press:
      - light.toggle: light_1
    on_click:
      min_length: 10s
      max_length: 30s
      then:
        - button.press: restart_button
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Touchpad 2"
    disabled_by_default: true
    on_press:
      - light.toggle: light_2
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Touchpad 3"
    disabled_by_default: true
    on_press:
      - light.toggle: light_3
  - platform: status
    name: "Status"
